export const SEL = {
  input: '[role="textbox"][aria-label="Message input"]',
  chip: '[data-reference]',
  chipRemoveBtn: '[data-remove="true"]',
  mentionsDropdown: '[role="listbox"][aria-label="Suggestions"]',
  mentionOption: '[role="option"]',
  addButton: '[aria-label="Add a tab, workflow or file"]',
  modelButton: 'button[aria-label^="Change model, "]',
  modelSearch: 'input[aria-label="Search models"]',
  modelDropdown: '[role="listbox"][aria-label="Select model"]',
  sendButton: '[aria-label="Send message"]',
  cancelButton: '[aria-label="Cancel"]',
  sendCount: '[aria-label="Send count"]',
  lastInteraction: '[aria-label="Last interaction"]',
  stateRadio: (name: string) => `[role="radio"][aria-checked]`,
} as const;
